logLevel = "DEBUG"

defaultEntryPoints = ["https","http"]

[docker]
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false

[metrics]
    [metrics.prometheus]

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]

[acme]
email = "user@example.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
    [acme.httpChallenge]
    entryPoint = "http"